name : Node.js CI

on: 
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - run:
          echo indigo | sudo -S npm i npm run build --if-present
